title: KANG LI (李康)
description: PhD Canditate of Tongji University, Majoring in Civil Engineering
site_title: '@KANG LI'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: KANGLI2021
blog_url: https://www.nagekar.com
email: kaangli@outlook.com
keybase_username: KANG LI
twitter_username: KEN_LLL
reddit_username: NONE

# absolute or relative
profile_picture: assets/images/kangli.jpg

# Google Analytics ID
google_analytics: 
